name: beamsteering
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy
      - matplotlib
      - "BeamSteering[gui,notebooks] @ git+https://github.com/MarKo7s/BeamSteering.git@v1.0.0"
